### ISSUE TITLE
team 4 : OS Diagram

### ISSUE THREAD

**Issue by zaethovenn** [OS-Sketch/www.os-sketch.com#3]
(Lead: zack, Associate: Favour) Create a diagram in excaladraw that shows the components of an operating system and how they interact. Also we have to describe what the components do in particular. We must save it as an sgv file and import into the repo. The diagram must be compatible with light and dark mode.

**Comment by gkapfham** [comment]
Hello @zaethovenn, thanks for raising this issue, I appreciate it!

You need to make sure that you create your diagram using this web site: https://excalidraw.com/

It is important that you create a diagram that is visible on both mobile and desktop devices. You also need to ensure that you have a "normal" and "inverse" version of your image so that it looks good on both the light and dark themes for the site. Please study the example image and source code that is already in the GitHub repository for some examples.

When you export your technical diagram, please make sure that you save in the GitHub repository an SVG, a PNG, and the actual Excalidraw file. We need to have all three of these files so that we can edit the image as needed and then also have files that we can use for different purposes. For instance, it is possible to edit the SVG file in your text editor and then control things like the displayed font and the colors. You will also need to follow special instructions (I can share them with you later) about how to embed the required font into the SVG files so that it displays in a fashion like what you see in Excalidraw.

It is also important to ensure that you create a diagram that reflects the course content that the team creating the schedule expects to cover. For instance, you don't want to include a component of an operating system in your diagram if we don't plan to cover it during the Fall 2022 semester. You also need to ensure that your diagram uses the same terms as are included in the book and the course schedule. Overall, you want your diagram to be a "visual roadmap" for all of the content that we will cover during the Fall 2022 semester.

Finally, please don't forget that you need to have a description of each key component in your diagram, including the name of the component, a description of its input and output, and what the component does to transform the input into the output. You should write this content in such a way that we can feature it on the web site!

**Comment by gkapfham** [comment]
Hello @zaethovenn and @favourojo and the technical diagram team!

Do you have a draft of the technical diagram that we can preview?

Please make sure that you track PR #9 so that you can see topics that your colleagues are proposing to study this semester.

Do you have a timeline by which you are prepared to complete the technical diagram and write a description of each major component in your diagram?

**Comment by favourojo** [comment]
![Screenshot from 2022-09-06 08-22-56](https://user-images.githubusercontent.com/54807906/188633990-6cbfe336-9688-4ff0-ab74-ce859270a878.png)

Yes, here is the preview of our diagram so far. We are still making some alterations as well to make it complete.
