### ISSUE TITLE
[Feedback] Learning Objectives - /operating-systems/learning-objectives/

### ISSUE THREAD

**Issue by cheng-cs** [OS-Sketch/www.os-sketch.com#6]
TEAM 5 (Learning Objective)

Describe what we learn in class. 

In more detail, we need to demonstrate how to use what we learn in class. We are also required to create a summary for each section we go over in class, starting from (8/30/2022).

**Comment by gkapfham** [comment]
Hello @cheng-cs, thanks for raising this issue!

First, you may want to refer to this web site for an example of a completed list of learning objectives:

https://proactiveprogrammers.com/discrete-structures/learning-objectives-discrete-structures/

You will need to collaborate with the team that is defining the course schedule. Specifically, please make sure that for every module of the course that they design you have learning objectives for that content.

Remember, when you are writing a learning objective you should almost always avoid using the word "understand". For instance, don't write the learning objective as "understands how the operating system ..." because it is not clear how we would know that a learner actually understands that specific topic. Instead, you should make sure that the learning objectives use action words and describe an action that, when observed, would help us to know that a person understands something.

You also need to make sure that all of the learning objectives are both clear and measurable. You should write a draft of the learning objective and then as another member of your team and/or the instructor to review it to ensure its correctness. Remember that all learners will be bound by these objectives!

Here are some articles to read about creating learning objectives:

https://rtalbert.org/steps-toward-excellence-the-power-of-learning-objectives/
https://rtalbert.org/how-to-write-learning-objectives/

Finally, you will need to seek feedback from the all course members to ensure that they agree with your learning objectives.

**Comment by gkapfham** [comment]
Hello @cheng-cs and the learning objectives team!

Please make sure that you are tracking PR #9 as it includes a draft of the course schedule.

What is the timeline that you plan to follow so as to complete the learning objectives that connect to the topics covered in the course schedule?

Please share more details here so that everyone is aware of your plans and your current status.
